stages:
  - parent-stage
  - parent-second-stage

parent job:
  stage: parent-stage
  script:
    - echo "Building things in parent pipeline ..."

parent second job:
  stage: parent-second-stage
#  script:                        # jobs:parent second job config these keys cannot be used together: script, trigger
#    - echo "Triggering job in child pipeline ..." 
  trigger:
    include:
      - local: /downstream-pipelines/child-pipeline.yml

# https://docs.gitlab.com/ee/ci/pipelines/downstream_pipelines.html

# Put this to .gitlab-ci.yml file:
# include: '/downstream-pipelines/parent-pipeline.yml'