include: '/include/override/override.yml'

variables:
  POSTGRES_USER: testing_user
  POSTGRES_PASSWORD: testing_password

stages:
  - main-stage

build:
  stage: main-stage
  script:
    - echo "Building things from main stage..."
    - echo "Postgres user is $POSTGRES_USER"
    - echo "Postgres password is $POSTGRES_PASSWORD"

# Put this to .gitlab-ci.yml file:
# include: '/include/override/override-main.yml'

# https://docs.gitlab.com/ee/ci/yaml/includes.html#override-included-configuration-values
