variables:
  POSTGRES_USER: testing_user
  POSTGRES_PASSWORD: testing_password

stages:
  - main-stage

build:
  stage: main-stage
  interruptible: true
  script:
    - echo "Building things from main stage..."
    - echo "Postgres user is '$POSTGRES_USER'"
    - echo "Postgres password is '$POSTGRES_PASSWORD'"
    - echo "The job's stage is '$CI_JOB_STAGE'"