variables:
  POSTGRES_USER: testing_user
  POSTGRES_PASSWORD: testing_password

stages:
  - main-stage

build:
  stage: main-stage
  interruptible: true
  script:
    - echo "Building things from main stage..."
    - echo "Postgres user: $POSTGRES_USER"
    - echo "Postgress password: $POSTGRES_PASSWORD"